version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "5000:80"
    networks:
      - ecommerce_network
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - ecommerce_network

  db:
    build: ./database
    restart: always
    environment:
      POSTGRES_DB: irede
      POSTGRES_USER: cauan
      POSTGRES_PASSWORD: cauan
    ports:
      - "5432:5432"
    networks:
      - ecommerce_network

networks:
  ecommerce_network:
    driver: bridge