services:
  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "5173:80"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: irede
      POSTGRES_USER: cauan
      POSTGRES_PASSWORD: cauan
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: