version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "80:80"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: cauan
      POSTGRES_PASSWORD: cauan
      POSTGRES_DB: irede
    ports:
      - "5432:5432"
